version: '3'

services:
  site:
   build: .
   stdin_open: true
   tty: true
   ports:
     - "8090:8090"
   volumes:
     - "/app/node_modules" 
     - ./:/app
   #environment:
   #  - NODE_ENV=development
   #  - CHOKIDAR_USEPOLLING=true
